pipeline {
    agent any

    environment {
        BRANCH='main'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/vinodravi84/Dev.git'
            }
        }

        stage('Build') {
            steps {
                sh 'docker-compose build'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}
